version: '3'

services:
    db:
        image: postgres:16
        restart: always
        environment:
            POSTGRES_DB: house
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
        ports:
            - "8101:5432"
        container_name: db
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend
        volumes:
            - .:/var/www/html
        ports:
            - "8001:80"
